// TODO add kconfig instead of this caveman style

#define IMU_PUBLISH_LOOP_DELAY_MS 10U
#define RC_INPUT_PUBLISH_LOOP_DELAY_MS 200U
#define RC_INPUT_CONNECTED_PUBLISH_LOOP_DELAY_MS 100U // Used to determine if ros is connected
#define BMS_PUBLISH_LOOP_DELAY_MS 200U
#define WHEEL_ENC_PUBLISH_LOOP_DELAY_MS 50U
#define INA3221_PUBLISH_LOOP_DELAY_MS 200U
#define ROS_SPIN_LOOP_DELAY_MS 10U
#define ROS_TIME_SYNC_LOOP_DELAY_MS 1000U