// TODO add kconfig instead of this caveman style

/* Helpers */
#define DIV_ROUND_CLOSEST(n, d) (((n) + (d) / 2) / (d))
#define MAX_U(a, b) ((uint32_t)((a) > (b) ? (a) : (b)))

/* Convert Hz → milliseconds, rounded, never 0 ms */
#define HZ_TO_MS(hz) MAX_U(1U, (uint32_t)DIV_ROUND_CLOSEST(1000U, (hz)))

/* Frequencies (Hz) */
#define IMU_PUBLISH_HZ 50U
#define RC_INPUT_PUBLISH_HZ 10U
#define RC_INPUT_CONNECTED_PUBLISH_HZ 500U
#define BMS_PUBLISH_HZ 1U
#define WHEEL_ENC_PUBLISH_HZ 50U
#define INA3221_PUBLISH_HZ 10U
#define CONTROL_LOOP_HZ 100U
#define ROS_SPIN_HZ 100U
#define ROS_TIME_SYNC_HZ 1U

/* Derived delays (ms) */
#define IMU_PUBLISH_LOOP_DELAY_MS HZ_TO_MS(IMU_PUBLISH_HZ)
#define RC_INPUT_PUBLISH_LOOP_DELAY_MS HZ_TO_MS(RC_INPUT_PUBLISH_HZ)
#define RC_INPUT_CONNECTED_PUBLISH_LOOP_DELAY_MS HZ_TO_MS(RC_INPUT_CONNECTED_PUBLISH_HZ)
#define BMS_PUBLISH_LOOP_DELAY_MS HZ_TO_MS(BMS_PUBLISH_HZ)
#define WHEEL_ENC_PUBLISH_LOOP_DELAY_MS HZ_TO_MS(WHEEL_ENC_PUBLISH_HZ)
#define INA3221_PUBLISH_LOOP_DELAY_MS HZ_TO_MS(INA3221_PUBLISH_HZ)
#define CONTROL_LOOP_DELAY_MS HZ_TO_MS(CONTROL_LOOP_HZ)
#define ROS_SPIN_LOOP_DELAY_MS HZ_TO_MS(ROS_SPIN_HZ)
#define ROS_TIME_SYNC_LOOP_DELAY_MS HZ_TO_MS(ROS_TIME_SYNC_HZ)