CONFIG_MICROROS_WIFI_SSID="sml_legacy"
CONFIG_MICROROS_WIFI_PASSWORD="SML4admin."

CONFIG_WIFI_CREDENTIALS=y
CONFIG_WIFI_CREDENTIALS_STATIC=y
CONFIG_WIFI_CREDENTIALS_STATIC_SSID="sml_legacy"
CONFIG_WIFI_CREDENTIALS_STATIC_PASSWORD="SML4admin."
CONFIG_MICROROS_AGENT_IP="10.0.0.157"
CONFIG_NET_CONFIG_WIFI_SSID="sml_legacy"
CONFIG_NET_CONFIG_WIFI_PSK="SML4admin."